# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887b6877555378b4dbd3ccf712fde00c939317c7e6a230d43f7ee15a3a65e7fe8acd04df80f796c48b583f7f335ef6e166b070c5ddadc885234f25a258fcdcb0

test:
  secret_key_base: 756310e22cdf4fc9d53ad8179211d48d7a1a89a9cfabf2359adea99f600802434f5e789343785b495b7f3ee41e18725abc5f061bcff80058c69cacdda7f130d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
